supercharged_analyst:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: oauth
      project: "{{ env_var('BQ_PROJECT') }}"
      dataset: dbt_dev
      threads: 4
      timeout_seconds: 300
      location: us-central1
    prod:
      type: bigquery
      method: service-account-impersonation
      project: "{{ env_var('BQ_PROJECT') }}"
      dataset: dbt_prod
      impersonate_service_account: "{{ env_var('DBT_SERVICE_ACCOUNT') }}"
      threads: 4
      timeout_seconds: 300
      location: us-central1
    cloudrun:
      type: bigquery
      method: oauth
      project: "{{ env_var('BQ_PROJECT') }}"
      dataset: staging   # all models use +schema overrides; this dataset already exists
      threads: 4
      timeout_seconds: 300
      location: us-central1
